# Generated by Django 5.1.5 on 2025-02-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('room_no', models.CharField(max_length=10)),
                ('mis', models.CharField(max_length=15, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('year', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=50)),
            ],
        ),
    ]
