# Generated by Django 5.1.5 on 2025-02-08 05:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_absenteerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('lunch_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('dinner_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
